Repository mindflayer-vtt/foundryvtt-mindflayer-brainmate, pull requests merged in 2022-03, with the labels that each got.

#10 fix: reenable app-menu and hid list header texts as they do not line …
  src/sass/index.sass
Labels: bug

#12 docs: improved README.md
  README.md
Labels: documentation

#14 feat(#13): implemented notification sound for new messages when chat is in background
  README.md
  src/js/Brainmate.js
  src/js/index.js
  src/sass/index.sass
Labels: enhancement

#15 fix: remove notification sound from desktop
  src/js/Brainmate.js
Labels: bug
